version: "3"
services:
  react-app:
    build: ./src/react_app
    ports:
      - "3000:3000"
    volumes:
      - ./src/react_app:/app
  flask-app:
    build: ./src/flask_app
    ports:
      - "8000:8000"
    volumes:
      - ~/.secrets:/app/.secrets
      - ./src/flask_app:/app
  redis-app:
    image: redis
    ports:
      - "6379:6379"
